# Generated by Django 2.0.6 on 2018-07-18 19:11

from django.db import migrations
import pwdj.core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pwdj.core.managers.UserManager()),
            ],
        ),
    ]
