# Generated by Django 2.0.6 on 2018-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='foto',
            field=models.ImageField(max_length=200, null=True, upload_to='galeria/'),
        ),
    ]
